learner:
    framework: MAT
    algorithm: TTT
    tester: WP-Method
    impIP: adapter
    impPort: 3333
    runsPerQuery: 4
    confidence: 85
    maxAttempts: 100
    inputAlphabet:
        # - INITIAL(?,?)[CRYPTO]
        # - INITIAL(?,?)[ACK,HANDSHAKE_DONE]
        # - HANDSHAKE(?,?)[ACK,CRYPTO]
        # - HANDSHAKE(?,?)[ACK,HANDSHAKE_DONE]
        # - SHORT(?,?)[ACK,MAX_DATA,MAX_STREAM_DATA]
        # - SHORT(?,?)[ACK,STREAM]
        # - SHORT(?,?)[ACK,HANDSHAKE_DONE]
        - SYN(?,?,0)
        - SYN+ACK(?,?,0)
        - ACK(?,?,0)
        - ACK+PSH(?,?,16)
        - FIN+ACK(?,?,0)
        - RST(?,?,0)
        - ACK+RST(?,?,0)
adapter:
    port: 3333
    impAddress: implementation
    impPort: 44344
    timeout: 0.4
    interface: eth0
    oracleTableURL: postgresql://prognosis:prognosis@database/prognosis
synthesizer:
    protocol: TCP
    adapter_ip: adapter
    adapter_port: 3333
    dot: /data/learner/learnresult.dot
    oracle_table: /data/adapter/oracleTable.json
