version: '3.8'
services:
  implementation:
    build: ./implementations/quiche
    init: true
    tty: true
    ports:
      - "4433:4433/udp"
    environment:
      - RUST_BACKTRACE=1
  adapter:
    build:
      context: ./adapter
    ports:
      - "3333:3333"
    links:
      - implementation
    volumes:
      - ./output/adapter/:/root
  learner:
    build: ./learner
    links:
      - adapter
    volumes:
      - ./output/learner/:/usr/src/learner/output/
