version: '3.8'
services:
  implementation:
    image: docker.pkg.github.com/ucl-pplv/quic-learner/implementation:msquic
    init: true
    tty: true
    ports:
      - "4433:4433/udp"
    environment:
      - RUST_BACKTRACE=1
  adapter:
    build:
      context: ./adapter
    environment:
      - HTTP3=0
      - PERFORMANCE_MODE=0
    ports:
      - "3333:3333"
    links:
      - implementation
    volumes:
      - ./output/adapter/:/root
  learner:
    build: ./learner
    links:
      - adapter
    volumes:
      - ./output/learner/:/usr/src/learner/output/
