version: '3.8'
services:
  implementation:
    image: docker.pkg.github.com/ucl-pplv/prognosis/implementation:quiche
    platform: linux/amd64
    init: true
    tty: true
    privileged: true
    ports:
      - "4433:4433/udp"
      - "44344:44344/tcp"
    sysctls:
      net.ipv4.tcp_syncookies: 0
    volumes:
      - ./output/implementation:/output/ 
  adapter:
    platform: linux/amd64
    build:
      context: ./adapters/quic
      #context: ./adapters/tcp
    privileged: true
    ports:
      - "3333:3333"
    links:
      - implementation
    volumes:
      - ./config.yaml:/root/config.yaml
      - ./output/adapter/:/root
    sysctls:
      net.ipv4.tcp_syncookies: 0
  learner:
    platform: linux/amd64
    build: ./learner
    links:
      - adapter
    volumes:
      - ./config.yaml:/usr/src/learner/config.yaml
      - ./output/learner/:/usr/src/learner/output/
      - ./output/cache/:/usr/src/learner/cache/
  synthesizer:
    image: docker.pkg.github.com/ucl-pplv/prognosis/synthesizer:latest
    platform: linux/amd64
    links:
      - adapter
    volumes:
      - ./config.yaml:/code/config.yaml
      - ./output/learner/final/:/data/learner/
      - ./output/adapter/:/data/adapter/

