version: '3.8'
services:
  implementation:
    image: docker.pkg.github.com/ucl-pplv/quic/implementation:quiche
    platform: linux/amd64
    init: true
    tty: true
    privileged: true
    ports:
      - "4433:4433/udp"
      - "44344:44344/tcp"
    environment:
      - RUST_BACKTRACE=1
      #- SSLKEYLOGFILE=/output/key
      #- QLOGDIR=/output
      #- RUST_LOG=trace
    sysctls:
      net.ipv4.tcp_syncookies: 0
    volumes:
      - ./output/implementation:/output/ 
  adapter:
    platform: linux/amd64
    build:
      context: ./adapter/quic
      #context: ./adapter/tcp
    environment:
      - HTTP3=1
      - TRACING=0
      - WAIT_TIME=400ms
      - HTTP_PATH=/
    privileged: true
    ports:
      - "3333:3333"
    links:
      - implementation
    volumes:
      - ./output/adapter/:/root
    sysctls:
      net.ipv4.tcp_syncookies: 0
  learner:
    platform: linux/amd64
    build: ./learner
    links:
      - adapter
    volumes:
      - ./config.yaml:/usr/src/learner/config.yaml
      - ./output/learner/:/usr/src/learner/output/
