version: '3.8'
services:
  implementation:
    image: ghcr.io/ucl-pplv/prognosis/implementation:tcp
    platform: linux/amd64
    init: true
    tty: true
    privileged: true
    ports:
      - "4433:4433/udp"
      - "44344:44344/tcp"
    sysctls:
      net.ipv4.tcp_syncookies: 0
    volumes:
      - ./output/implementation:/output/ 
  adapter:
    build:
      #context: ./adapters/quic
      context: ./adapters/tcp
    privileged: true
    platform: linux/amd64
    depends_on:
      - "implementation"
    ports:
      - "3333:3333"
    volumes:
      - ./config.yaml:/root/config.yaml
      - ./output/adapter/:/root
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #sysctls:
      #net.ipv4.tcp_syncookies: 0
  learner:
    build: ./learner
    platform: linux/amd64
    depends_on:
      - "adapter"
    volumes:
      - ./config.yaml:/usr/src/learner/config.yaml
      - ./output/learner/:/usr/src/learner/output/
      - ./output/cache/:/usr/src/learner/cache/
  synthesizer:
    build: ./Synthesis
    depends_on:
      - "adapter"
    volumes:
      - ./config.yaml:/code/config.yaml
      - ./output/learner/final/:/data/learner/
      - ./output/adapter/:/data/adapter/
      - ./output/synth/:/data/synth/
