os:
  - linux
  - osx

language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"

addons:
  apt:
    packages:
      - tcpdump
      - libpcap-dev
      - openssl
      - libssl-dev
      - faketime
      - libscope-guard-perl
      - libtest-tcp-perl
  homebrew:
    packages:
      - openssl
      - libpcap
      - tcpdump
      - libfaketime

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CMAKE_OPTS=" -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://cpanmin.us | sudo perl - App::cpanminus; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpanm --notest Scope::Guard; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo cpanm --notest Test::TCP; fi

install:
  - go get -t -v ./... || true
  - cd $GOPATH/src/github.com/mpiraux/pigotls && make
  - cd $GOPATH/src/github.com/mpiraux/ls-qpack-go && make
  - cd $GOPATH/src/github.com/QUIC-Tracker/quic-tracker

script:
  - go test
  - go build bin/test_suite/test_suite.go
  - go build bin/test_suite/scenario_runner.go
  - go build bin/http/http_get.go
